name: Compute Sum of Random Numbers

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  compute-random-sum:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Generate 10 random numbers and compute sum
      id: random-sum
      run: |
        python3 -c "
        import random
        numbers = [random.randint(1, 100) for _ in range(10)]
        total = sum(numbers)
        print(f'Random numbers: {numbers}')
        print(f'Sum: {total}')
        print(f'sum={total}' >> '$GITHUB_OUTPUT')
        "
    
    - name: Display result
      run: |
        echo "The sum of 10 random numbers is: ${{ steps.random-sum.outputs.sum }}" 